config/routes.rb
Rails.application.routes.draw do

  resources :mycelia do
    resources :substrate_runs
    resources :spawn_runs
    resources :lc_runs do
      resources :log_entries, module: :lc_runs
    end
    resources :petri_runs do
      resources :log_entries, module: :petri_runs
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/mycelia_controller.rb
class MyceliaController < ApplicationController
  before_action :set_mycelium, only: [:show, :edit, :update, :destroy]

  # GET /mycelia
  # GET /mycelia.json
  def index
    @mycelia = Mycelium.all
  end

  # GET /mycelia/1
  # GET /mycelia/1.json
  def show
  end

  # GET /mycelia/new
  def new
    @mycelium = Mycelium.new
  end

  # GET /mycelia/1/edit
  def edit
  end

  # POST /mycelia
  # POST /mycelia.json
  def create
    @mycelium = Mycelium.new(mycelium_params)

    respond_to do |format|
      if @mycelium.save
        format.html { redirect_to @mycelium, notice: 'Mycelium was successfully created.' }
        format.json { render :show, status: :created, location: @mycelium }
      else
        format.html { render :new }
        format.json { render json: @mycelium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mycelia/1
  # PATCH/PUT /mycelia/1.json
  def update
    respond_to do |format|
      if @mycelium.update(mycelium_params)
        format.html { redirect_to @mycelium, notice: 'Mycelium was successfully updated.' }
        format.json { render :show, status: :ok, location: @mycelium }
      else
        format.html { render :edit }
        format.json { render json: @mycelium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mycelia/1
  # DELETE /mycelia/1.json
  def destroy
    @mycelium.destroy
    respond_to do |format|
      format.html { redirect_to mycelia_url, notice: 'Mycelium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mycelium
      @mycelium = Mycelium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mycelium_params
      params.require(:mycelium).permit(:name)
    end
end

app/helpers/mycelia_helper.rb
module MyceliaHelper
end

app/views/mycelia/_form.html.erb
<%= form_with(model: mycelium, local: true) do |form| %>
  <% if mycelium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mycelium.errors.count, "error") %> prohibited this mycelium from being saved:</h2>

      <ul>
        <% mycelium.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mycelia/edit.html.erb
<h1>Editing Mycelium</h1>

<%= render 'form', mycelium: @mycelium %>

<%= link_to 'Show', @mycelium %> |
<%= link_to 'Back', mycelia_path %>

app/views/mycelia/index.html.erb
<div class="card-header d-flex justify-content-between">
  <span>
  My Mushrooms
  </span>
  <%= link_to 'Add New Mushroom', new_mycelium_path, class: 'btn btn-info btn-sm' %>
</div>


  <ul class='list-group'>
    <% @mycelia.each do |mycelium| %>
      <li class='list-group-item'>
        <%= link_to mycelium.name, mycelium %>
      </li>
    <% end %>
  </ul>

app/views/mycelia/new.html.erb
<h1>New Mycelium</h1>

<%= render 'form', mycelium: @mycelium %>

<%= link_to 'Back', mycelia_path %>

app/views/mycelia/show.html.erb
<div class="card-header d-flex justify-content-between">
  <span>
  Myshroom: <%= @mycelium.name %>
  </span><%= link_to 'Edit', edit_mycelium_path(@mycelium), class: 'btn btn-info btn-sm' %>
  <%= link_to 'Back', mycelia_path, class: 'btn btn-info btn-sm' %>
</div>


  <ul class='list-group'>
    <div>
      <%=link_to 'Petri Dishes', mycelium_petri_runs_path(@mycelium),  class: 'btn btn-info btn-sm' %>
      <%= link_to 'New Petri dish', mycelium_petri_runs_path(@mycelium), class: 'btn btn-info btn-sm' %>
    </div>
    <% @mycelium.petri_runs.each do |petri_run| %>
      <li class='list-group-item'>
        <%= link_to petri_run.strain, [petri_run.mycelium, petri_run] %>
      </li>
    <% end %>
  </ul>
  <ul class='list-group'>
    <div>
      <%=link_to 'Liquid cultures', mycelium_petri_runs_path(@mycelium),  class: 'btn btn-info btn-sm' %>
      <%= link_to 'New Liquid culture', mycelium_petri_runs_path(@mycelium), class: 'btn btn-info btn-sm' %>
    </div>
      <% @mycelium.petri_runs.each do |petri_run| %>
        <li class='list-group-item'>
          <%= link_to petri_run.strain, [petri_run.mycelium, petri_run] %>
        </li>
      <% end %>
    </ul>
  <ul class='list-group'>
    <div>
      <%=link_to 'Spawn', mycelium_petri_runs_path(@mycelium),  class: 'btn btn-info btn-sm' %>
      <%= link_to 'New Spawn', mycelium_petri_runs_path(@mycelium), class: 'btn btn-info btn-sm' %>
    </div>
    <% @mycelium.petri_runs.each do |petri_run| %>
      <li class='list-group-item'>
        <%= link_to petri_run.strain, [petri_run.mycelium, petri_run] %>
      </li>
    <% end %>
  </ul>
  <ul class='list-group'>
    <div>
      <%=link_to 'Grow Run', mycelium_petri_runs_path(@mycelium),  class: 'btn btn-info btn-sm' %>
      <%= link_to 'New Grow run', mycelium_petri_runs_path(@mycelium), class: 'btn btn-info btn-sm' %>
    </div>
    <% @mycelium.petri_runs.each do |petri_run| %>
      <li class='list-group-item'>
        <%= link_to petri_run.strain, [petri_run.mycelium, petri_run] %>
      </li>
    <% end %>
  </ul>